include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options


analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    dead_code: warning
    unused_import: warning

linter:
  rules:
    avoid_print: true
    prefer_relative_imports: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_unnecessary_containers: true
    unnecessary_this: true
    sized_box_for_whitespace: true
    use_super_parameters: true
    sort_constructors_first: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    avoid_redundant_argument_values: true
    unnecessary_lambdas: true
    depend_on_referenced_packages: false
