name: manga_page_view
description: "A Flutter widget designed for comic and manga page reader"
version: 1.0.0
homepage: https://github.com/amuhaimin02/manga_page_view
repository: https://github.com/amuhaimin02/manga_page_view

environment:
  sdk: ^3.0.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
