name: manga_page_view
description: "A widget for comic/manga page reader"
version: 1.0.0
homepage: https://github.com/amuhaimin02/manga_page_view
repository: https://github.com/amuhaimin02/manga_page_view

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
